### PR TITLE
Core20 and prepare for mir-kiosk-snap-launch update

### PR DESCRIPTION
**Pull request by AlanGriffiths**

### CODE REVIEW

**Review by wmww — APPROVED** [review]
LGTM

**Review by wmww — CHANGES_REQUESTED** [review]
When I build I get
```
Failed to generate snap metadata: The specified command 'bin/scummvm-launch' defined in the app 'daemon' is not executable.
```

**Comment by AlanGriffiths** [comment]
> When I build I get
> 
> ```
> Failed to generate snap metadata: The specified command 'bin/scummvm-launch' defined in the app 'daemon' is not executable.
> ```

Weird, I don't get that.

```plain
$ snapcraft --version
snapcraft, version 4.3
```

**Comment by wmww** [comment]
I'm on Ubuntu 20.04 with snapcraft 4.3 as well, and I'm still getting
```
Failed to generate snap metadata: The specified command 'bin/scummvm-launch' defined in the app 'daemon' is not executable.
```
Maybe try a clean build? Since I'm the one who can reproduce this I'll try to fix it tomorrow if you haven't already.

**Comment by AlanGriffiths** [comment]
> Maybe try a clean build? Since I'm the one who can reproduce this I'll try to fix it tomorrow if you haven't already.

Still works. Also fine when `remote-build` on LP servers. (And builds here as a github action.)

I think the problem with your setup. Which `multipass` are you using? Which snapcraft options?

**Review by wmww — APPROVED** [review]
Multipass v1.4.0. Clean build still has the problem for me, but if I'm the only one seeing it it's fine.

**Pull request merged**
